### PR TITLE
Add test case for Issue#885

### PR DESCRIPTION
**Pull request by RaymondHuy**
Issue autofac/Autofac/issues/885 has already been fixed, just add test case for it.

### CODE REVIEW

**Comment by alistairjevans** [comment]
If https://github.com/autofac/Autofac/issues/885, has been fixed, shouldn't a test for the fix be added in the Autofac repo? Is there a reason it's going in DynamicProxy?

Also, when you say that it's been fixed, it seems pretty tightly connected to https://github.com/autofac/Autofac/issues/925, which is still ongoing. 

Can you elaborate on what has changed that means https://github.com/autofac/Autofac/issues/885 is now fixed?

**Comment by RaymondHuy** [comment]
Hi @alistairjevans I see issue 925 is mentioning about issue 855 but my PR is targeting issue 885 (not 855). You can see in issue 885 the author is raising a bug about `EnableClassInterceptors` feature which belongs to Extras.DynamicProxy so I have to add the test case in this repo. (maybe the author has raised the issue in wrong repo.)

**Comment by alistairjevans** [comment]
Sorry, I wasn't clear. The reference to 925 is indirect via https://github.com/autofac/Autofac/issues/1027.

If the test only breaks in DynamicProxy, then it may have been raised in the wrong repo as you suggest.

**Comment by RaymondHuy** [comment]
Hi @alistairjevans after investigating this issue I see that the reason is about the version from Castle.Core. This issue has been fixed by changing the target version Castle.Core from 4.2.1 to 4.3.1 when upgrading Autofac.Extras.DynamicProxy version from 4.4.0 to 4.5.0. You can also reproduce this issue by check out the branch in this PR and just change the version of Castle.Core to 4.2.1.

**Review by alistairjevans — APPROVED** [review]
LGTM

**Comment by alistairjevans** [comment]
Aha, thanks for the investigation @RaymondHuy, good to have that written down somewhere. 

Merging this now.

**Pull request merged**
