### PR TITLE
Update Castle.Core version

### PR DESCRIPTION
**Pull request by sstassen-wowcorp**
See https://github.com/autofac/Autofac.Extras.DynamicProxy/issues/51

### CODE REVIEW

**Comment by alistairjevans** [comment]
Is it required that the Castle.Core dependency moves to the latest major version? Or can we move to the latest minor version in the 4.* branch and still resolve the issue?

**Comment by sstassen-wowcorp** [comment]
Thanks for follow up Alistair

I checked Castle.Core 4.4.1 and found the dependency on NETStandard1.6 persists, resulting in a dependency on System.Text.RegularExpressions 4.3.0.

Castle.Core >= 5.0.0 takes a dependency on NETStandard2.1, which has no System.Text.RegularExpressions dependency

**Comment by alistairjevans** [comment]
OK, that checks out; I think it's reasonable to update the library, besides, this library only targets netstandard2.0 and 2.1 anyway.

I think we should probably label it as a breaking change though, since we force the breaking changes from `Castle.Core`, so can you also please update `appveyor.yml` and change the 2 version fields to `7.0.0`? Then we can merge.

**Review by alistairjevans — APPROVED** [review]
🐱‍💻

**Pull request merged**
